// right-sidebar/src/App.vue
<template>
  <div class="right-sidebar">
    Your Vue Application is successfully loaded
  </div>
</template>

<script>

export default {
  name: 'App',
}
</script>

<style>
.right-sidebar{
  background-color: grey;
  font-size: 18px;
  font-weight: bold;
  text-align: center;
  height:100%;
  display: flex;
  justify-content: center;
  align-items: center;
}
</style>

// footer/src/App.svelte
<script>
</script>

<div class="footer">
	Your Svelte application is successfully loaded
</div>
<style>
	.footer{
		background-color: lightgrey;
		font-size: 18px;
		font-weight: bold;
		text-align: center;
		height:100%;
		display: flex;
		justify-content: center;
		align-items: center;
	}

</style>
